
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main '$remote_addr - $ssl_client_s_dn - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"Client fingerprint" $ssl_client_fingerprint '
                    '"TLS" $ssl_protocol/$ssl_cipher $ssl_ciphers'
                    '"serial" $ssl_client_serial'
                    '"$http_user_agent" "$upstream_response_time"';

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
  proxy.conf: |
    # upstream node_basic {
    #     server                  node_basic:80;
    # }

    # server {
    #     listen                  80;
    #     location / {
    #         return              301 https://$host$request_uri;
    #     }
    # }

    server {
        listen                  443 ssl;

        ssl_certificate           /etc/ssl/server.crt;
        ssl_certificate_key       /etc/ssl/server.key;
        ssl_protocols             SSLv2 SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers               ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv3:+EXP;
        ssl_client_certificate    /etc/nginx/client_certs/ca.crt;
        ssl_prefer_server_ciphers on;
        ssl_verify_client         on;
        ssl_verify_depth          10;

        location / {
            if ($ssl_client_verify != SUCCESS) { return 403; }

            proxy_set_header     Host $host;
            proxy_set_header     X-Real-IP $remote_addr;
            proxy_set_header     SSL_Client_Issuer $ssl_client_i_dn;
            proxy_set_header     SSL_Client $ssl_client_s_dn;
            proxy_set_header     SSL_Client_Verify $ssl_client_verify;

            proxy_pass           https://www.google.com.br;
        }
    }
  server.crt: |
    -----BEGIN CERTIFICATE-----
    MIIErDCCApQCAQEwDQYJKoZIhvcNAQELBQAwJDEiMCAGA1UEAwwZUXVhbnRvIERF
    ViBDZXJ0IEF1dGhvcml0eTAeFw0yMjAzMjAwMTQ0MjhaFw0yMzAzMjAwMTQ0Mjha
    MBQxEjAQBgNVBAMMCWxvY2FsaG9zdDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
    AgoCggIBANlA6PRlnjA/6ovAp/IR2pnAbY/TbX/1uZoxr1+PXqhoIXrphjhzgs2W
    DkLyO2DrsWrYZUawkkoXvMXzhg3514KsuHYEb7XvgNyauhermXsMn9KP5SOcRK0p
    PeGBoR+PElCilTfWUu1aywD+iNDbwvvTFbrjx0TS1ggwT9VI6DphIx6xQlIWjCtM
    991KH5gFNM7RdGSIP1ot7T62g4NA82YpIC+a3/YSZFxPZUrul8XCUFwyxywZkxSj
    nEhgw+9x77Jr/sg8Ddi/h2M1Gh9rr1V7uyRJNlorRNW20vJWwGPPH9B2g3nHFyRI
    1jvBdk1rmFA/wGumnf0H2kXxgC29nf47A3ct7m5I4BfuKjtwT0qDMUxI+qTYcSmZ
    ZWzQueLD3XC2sAtym5XW4bfrWAg5ACU6evyM3sOi+t6Bf3hnCEtsgON28aSedMTA
    479o+djwHgo2xoDXcQFITWeE0Ajw/KtMIgrqYJZo39W9uzM9GAKjmxWHNPM8xKeO
    1qIJUq9EW4gYb438AzHWwrBJu//hgNPgHWo5U77QR0YEqeP3wDeUQDYSNxKhK9fh
    1bT4YBA4m66Pv2XIRGSkh2gTRBIa5wKdVZ14Y/252l0NwI5MDJX3nacHTM2MuXZc
    3+VffV1UWRx594fvyvy/cF+Q7L6ZElfk8swW5MhxwDTmHjHYvtRzAgMBAAEwDQYJ
    KoZIhvcNAQELBQADggIBADUznP93JYkvxqHjWYZSiOAd/OuoQQNe5QINsaZLWDy2
    CMIW9cgcoxHQ3hY4DPwdCeWG/QotPilvZ3MBR1VPJRK0/aLKc64CQenpIsFo+8cP
    tkcffw4oo/eITkR3oOD/ldiSEYKKMSQ8kkEQgIkGZppTNq0ERr3uzZ2n1ZVOq2H/
    A8cVvzgt+31eE/tCfTkjhZ0k6ZnHEQm02Ihn/l3ozu45UjOr2A6ufd87DpbB54r/
    B+S5LjQGzx3QSJg3uFF63KaNhMe7IQwhzqnuHl+2TDwrds4+ErdFPaa+NaqZZ4k8
    CFsfCYOjkb8QJsqQ4SEqzix5ADA7X6W6IEGyVJjElipM/6ZHCAr38qxiMGU5lbBz
    BDkVA+HwcpniIO4n6lDSmLvHILie3y8Ldmqpt34H6Uu9IkvacE1H4kh0DU2WfuLn
    8uDim1pql+2O7Ud43Yca/ks/2sgiRqyUB5qhFbKMQ1bRIoAch56ajcSRX/JFWLlG
    gQOZr4mbY8U9PU9UpFsj9WZxxp0ffWfIykB/RTLCT7ynya3OBRt3Lt/uQElAcuVX
    DDD7TGtfrRQn/bipLaeiON7HqIzqTvcO+bJkG0QPZx+HEDQ64u2ItIoCqUFLImx1
    mW9LocgMHjqAv56yFcQb6Z8ZBOSeZwGH1uPGEIoAhgwxzIyMOsKItg3yqGXFR4B9
    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDZQOj0ZZ4wP+qL
    wKfyEdqZwG2P021/9bmaMa9fj16oaCF66YY4c4LNlg5C8jtg67Fq2GVGsJJKF7zF
    84YN+deCrLh2BG+174DcmroXq5l7DJ/Sj+UjnEStKT3hgaEfjxJQopU31lLtWssA
    /ojQ28L70xW648dE0tYIME/VSOg6YSMesUJSFowrTPfdSh+YBTTO0XRkiD9aLe0+
    toODQPNmKSAvmt/2EmRcT2VK7pfFwlBcMscsGZMUo5xIYMPvce+ya/7IPA3Yv4dj
    NRofa69Ve7skSTZaK0TVttLyVsBjzx/QdoN5xxckSNY7wXZNa5hQP8Brpp39B9pF
    8YAtvZ3+OwN3Le5uSOAX7io7cE9KgzFMSPqk2HEpmWVs0Lniw91wtrALcpuV1uG3
    61gIOQAlOnr8jN7DovregX94ZwhLbIDjdvGknnTEwOO/aPnY8B4KNsaA13EBSE1n
    hNAI8PyrTCIK6mCWaN/VvbszPRgCo5sVhzTzPMSnjtaiCVKvRFuIGG+N/AMx1sKw
    Sbv/4YDT4B1qOVO+0EdGBKnj98A3lEA2EjcSoSvX4dW0+GAQOJuuj79lyERkpIdo
    E0QSGucCnVWdeGP9udpdDcCOTAyV952nB0zNjLl2XN/lX31dVFkcefeH78r8v3Bf
    kOy+mRJX5PLMFuTIccA05h4x2L7UcwIDAQABAoICACFMhqg3Dxj8IvoKrHM481WP
    nftmf6kWQ71zkhrGgc60LzWEp5LteYYDUupF8H35gjcLNfKwy6tZmhCJM+neen7H
    9Hn6UhkDva+Sc6V/IsYueCyw64EayZf080wmL0kEB92eHdryGcHRob3kRZolpOwu
    PW1ozjkpS67zoLjjNN0F2Hky2CR22kMkx/T+EHufiKmOhxWFoJg04+Ex3lR21xe4
    g/tn9J3l0cYoUTE8Ar1H/EM1cTu8K8QFE8YwNrfzsbaaQPH16nVnXdwB3qAkRDqI
    /XUhV5hYe3N6UzjbvR9PNuQf1iULM+vW0idUjsptDGp4awjU//AxjO4dhvT71ERD
    8xlHArI/EeN7IcfQbBseh9lxeO7fMgHX8FO3laYR/kstICL+ZQAionoXvWaJdXSs
    2n6Dxgcphi/4KLsIDuOvlKz4c8WwOS9Vh9jnfhbjHPCAa6qLuezi9WnqX07Fzepz
    DnB/H+/9Ar66NCcPMJ7FQd5vXoY8oYA3/bJXWZLvrY1wFLu3WXopXXxTnwSuc2tQ
    5GATEFTa36eFRm0gdr9nyVypVeHYl44JB6SEt7kZSRsB6TSoGRfTmBuTAKJ8j41b
    bKHufcoDxITgIX0OS3Q3IM6psknKbVctSlVgwsseWQjFArtLP7ULQkUCAN7hE3Np
    zODJpokg+FEj9HBCcVkBAoIBAQD1fbsHytW8DBEha7K3PwfaGXwfb+Dvfxfr6LOp
    9M0VxzIGY6NY+6WPokPiTYTLWk7yR+8TclMwNTwzQwt7fWjClEKUQdaOF9U6bBrY
    RlXlDook1Jodu9mW3rsEaMtnC8/P0/g8WVsArCmY8Cjl28+H+G63SxR5omGH/Fwh
    DcuXCcm15grw0bvJEHHaKP7XEeZtkwiYxgz0F6tUVYiNG+p1VTYnYzvnaiXX0iqZ
    v55rnILcXizr4PNH4jji2gykoM5mZEMVYrHEaRWXUwKQu159Jyofi6j4YKciqlrm
    6ism16XyCKfGYrvyxkZ9bhmnxIxnrll2t8jZ+DDpQlkdCjqBAoIBAQDijbtHmhiY
    I+ize04ggqz4EqPpXEVy0wBf4UwNEkNVVnarUiNGtVu1TafQ4mR3nNzf9c1SKZFC
    ZFgO3JiH5Z6hqGprjKg35NwwbJ9BcSn3hInl8/dohl+2eIOt9yB1DQMdrkqbDl10
    7QIh6pWigF+12y+V9gLe+HS6k8WwgmdT54SX8zRk2HqYCiAHdTrAxzbwa58WKGsO
    gagsHPEYObmZIECoX5h6d2PIx5XHIsf3ZizFSl9wG5N+pPNfTULtd9NyjZ61r8Gc
    OvQb65do1XJvwii9bLKXRj2joP7VpJsFT7z4pFLFC8jxYXvGGVFTninAy8kIbY7v
    VmYzgpDrK0zzAoIBAQDC2839XW9SGHHwiUAOXCWrZNc1TOTKtaMTSl5x5TJ0uuxm
    Teh21SiRXkdr9gQWNdS8U4Tddr25YkgqmGkg2GazLGO8spXPq/NAsFaOnSXI70WP
    /oFmYJlSO/FOirAJV0LYwHQl0vd9DSrnjpmn+lY8o2GedCYIdm/cNOAcDIsxlD9b
    9wFwLcpUyozUkf3WUQsKps8IFQxrI+6Gvm3pM+NixwR5NzdxdLwdF2FhMMxatpzY
    tpgJk0EIKfTlfBbVBh9O/v6Qlwpr0M2mk+lRYKibxt6Us5KntHB1/6qv5+fgqQO7
    nksuGWj+R4vkO+R5WnXoRmgU58Sx32NTg6qgdmIBAoIBAGvw7W8TC27JhSCmujWh
    LTpQ30nbTbeEsuP72xlLP0uUk5vS2b3hwN0kL7XFd+rJkS8f1QC1j2EboB0Mm5v8
    GlWZgYLWlHt1DjgAOOycN0uYGX+3eoSRqV6uEsc7PHqohXiJx0ATWxHPrrlsJHk1
    QuTJluWTPhDwPeV7bLBJoWOHplQjay41OkvgXxxOjXy2LgXksPqErWVO/0ptS62o
    Kza6+DOAwIxw/9j0xvcHKlFEnEYvxkMK0H6BpvccP6wW8Gbe9ORJ5ixCpnX7DLvF
    Hu4CixidhoWu0MV6epBeCgJA2J9643jAwa/IK4naHDaD4A7cyV67nGOKPc2DAvsZ
    OWMCggEATvYsL+Ys9AftrVMSu/x+zhz45AuOmV0J6qkBRtYoWz6PrVxw4Ql4nLpy
    oD+8pWHgslAn1yxR2cD4xBaiKL8E85ZeR+dmSPZtLd1lFyeNc2H7+CgnotOCwZpS
    DafDW1h0J/I5YPvgm/mJ3YuJGt6laTsj2tNiQIVbwoThhLrT3+7DTmxV+Ob83PM0
    nttHiN45AT0MEt/RtjGymRtNpyqQwcF2a+3dTamHANLXi1kMs430Bl7Ietr7vr65
    EJPU7Dp28eeq3G/TzR9OkOLhFKZjQe3fh6g8rYki8slAElpZMMKyNi8dV5UDTPAe
    XLAV7lcI1nOP2VLUbbkMLHFwqJBcgA==
    -----END PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFKTCCAxGgAwIBAgIUIVgNn99YWmVxbE1SYtc3IRRu6rEwDQYJKoZIhvcNAQEL
    BQAwJDEiMCAGA1UEAwwZUXVhbnRvIERFViBDZXJ0IEF1dGhvcml0eTAeFw0yMjAz
    MjAwMTQ0MDRaFw0yMzAzMTEwMTQ0MDRaMCQxIjAgBgNVBAMMGVF1YW50byBERVYg
    Q2VydCBBdXRob3JpdHkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC5
    OPEf/xWjSuWW7UN4A23UuesUiyhN2WIoCg5P3BWE7Pwzn6m9pGA8pIQMCcs0Bd/u
    6wJeNefTYI25kktuMPfT/hRpDMksLowPs+PATt38LcC6fiIpaK8iAaTHUMvvIgFj
    HvAAABvAEnm/iuwbIxaft9JFrwO3ULD/1GJfgQy6+W7yjMtrWwV+UzFjuTDWbvsN
    3qPJc8bs92Doy+62CEzBqLDgD95DVaPRRueqRbTSHAJn0bjAq5iynvL0UiuSu3uc
    S2qWz1tTWnDUKLiFLGn1lPLNL4FN6C5CCswIWZfqpZ10N6Ue5RJROGqyDOOOvgE8
    dWJTkehfp3o+72cHKwbHSQHg7vObCou/+5iNCQCAbCWwG25V8pJei+8fP6zdnLH2
    5EiyWKoilCLEe8gqiEYvqSt9VkAJPR0MsdM6jxp4XrRB4DeTHpXutplmEuOIcZoY
    vltVzp98ONHz1SYdtVZK1aiIoJ5vcMgqYr7ruVDnd17i3Sp2AYu1xLNpH/n1jjAW
    ufwZ9QPCGEJQ3Zcf79diqp6Eb9Bh1/hiWXS/xJFq3rJ5hjwCmnfAEo4jufCQU2Xt
    SbN16Ymu0zxj92sqE/42kxRpMLebRhLJ3m5BVGANehDx/vZDnQ1IBAWbCb7yXUXX
    jf/t4+0aajl4X/276XGAokIIAW3n8btGOSqPP1FN1wIDAQABo1MwUTAdBgNVHQ4E
    FgQUdoJL8HmIelwXrxvny7iwhtYB5ekwHwYDVR0jBBgwFoAUdoJL8HmIelwXrxvn
    y7iwhtYB5ekwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEAYZO9
    FTRvuTOg3+8sW85f/+hhPbhYlFOQORfk3jFsZfKYjou+VBXD0x+qOOzGBhm9nMDB
    9OBC0WsqOqx/4dO09RTW31J3VEuoR08uBjVdTZabOgulho4Y43sinekhrVbSyB4R
    eeeqCmv2yX/uVfqaLFCev9xDN1MVNwOKN2xTyVgp3RRsUPJ2MqY30RK3m51buVkv
    2toJh09/Dg+ANE95QFLBcN3dDoaAXzrts6q5II9JThrA61bNliP5l55QfT3rv8oJ
    hmjomPrBrNPj1ls/K4POJvLTBdGhG0yWch8T7DE28Ij9e6cPEvXYf0zKX5nhQLQ4
    g6TxRXkVAfBs76OyDsW7trj1busmxz78ZUdGzYNh3gGMJe4ZnX0asQLUtLwHuZKv
    pmToLexYq6pmPkvDzZiThmLkW+M0YrECv4yeQUEGUYARXtH5EUalrc/9ioFOu0BC
    K/p5DGhoX1s2li8TkKRSg2OQWxopA24PbwGbS3Okkd2+P/jwoDxqqWTBVbphXowo
    M9NWCVDUpSSd9VNFaosOp4cPepI0O4n5mS8UpsZlxnIgxQts5TrKpZS3D+QHJCLS
    bEkLojr77oLfe6jFZp7UB8YZAzxpQe4jX5DDFcLDhVcWHBUmFSLsQW/crfT+JoVg
    I4hR+heA+XMqyg6Gp+F8XwhSah/RyDshLggjWTo=
    -----END CERTIFICATE-----
