apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: proxy.conf
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/ssl/server.crt
          subPath: server.crt
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/ssl/server.key
          subPath: server.key
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/client_certs/ca.crt
          subPath: ca.crt
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: proxy.conf
              path: proxy.conf
            - key: server.crt
              path: server.crt
            - key: server.key
              path: server.key
            - key: ca.crt
              path: ca.crt
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ops/workload
                operator: In
                values:
                - k8score
              - key: lifecycle
                operator: In
                values:
                - OnDemand